# Functions

## Variable number of arguments

While it may seem odd, it is sometimes useful to leave the number of
arguments unspecified. 

A simple example is a function that computes the
product of an arbitrary number of numbers:

In [ ]:
def product(*args): 
    print(args) 
    p = 1 
    for num in args: 
        p*= num  
    return p


In [ ]:
product(11., -2, 3)

In [ ]:
product(2.31, 7, 3,4,5,6,7,1,4,6,8,9,90,0,0)

```python
def product(*args): 
    print(args) 
    p = 1 
    for num in args: 
        p*= num  
    return p

```

The `print(args)` statement in the function definition is not
necessary, of course, but is put in to show that the argument `args` is
a tuple inside the function. 

## Variables and arrays created entirely within a function

Variables and arrays created
*entirely within* a function cannot be seen by the program that calls
the function unless the variable or array is explicitly passed to the
calling program in the `return` statement. 

This is important because it
means you can create and manipulate variables and arrays, giving them
any name you please, without affecting any variables or arrays outside
the function, even if the variables and arrays inside and outside a
function share the same name.


In [ ]:
def sinc(x):  
    z = np.where(x==0.0, 1.0, np.sin(x)/x) 
    return z

import numpy as np 
import matplotlib.pyplot as plt
%matplotlib inline

x = np.linspace(-10, 10, 256) 
y = sinc(x)
plt.plot(x, y) 
plt.show()

Running this program produces a plot like the plot of sinc shown in the
previous section. Notice that the array variable `z` is only defined
within the function definition of sinc. 

After running the cell above, if we ask
to print out the arrays, `x`, `y`, and `z`, we get some
interesting and informative results.

In [ ]:
x

In [ ]:
y

In [ ]:
z

## Passing variables and arrays to functions: mutable and immutable objects

What happens to a variable or an array passed to a function when the
variable or array is *changed* within the function? 

The answers are different depending on whether the variable passed is a
simple numeric variable, string, or tuple, or whether it is an array or
list. 

In [1]:
import numpy as np
def test(s, v, t, l, a):  
    s = "I am doing fine" 
    v = np.pi**2 
    t = (1.1, 2.9) 
    l[-1] = 'end'
    a[0] = 963.2 
    return s, v, t, l, a

s = "How do you do?" 
v = 5.0 
t = (97.5, 82.9, 66.7) 
l = [3.9, 5.7, 7.5, 9.3] 
a = np.array(l)

print('*************') 
print("s = %s" % (s)) 
print("v = %5.2f" % (v)) 
print("t = %s" % (str(t)))
print("l = %s" % (str(l)))
print("a = "), # comma suppresses line feed 
print(a)
print('*************') 
print('*call "test"*')

s1, v1, t1, l1, a1 = test(s, v, t, l, a)

print('*************') 
print("s1 = %s " % (s1))
print("v1 = %5.2f" % (v1)) 
print("t1 = %s" % (str(t1)))
print("l1 = %s" % (str(l1))) 
print("a1 = "), 
print(a1)
print('*************') 
print("s = %s " % (s)) 
print("v = %5.2f" % (v)) 
print("t = %s" % (str(t))) 
print("l = %s" % (str(l))) 
print("a = "), # comma suppresses line feed 
print(a)
print('*************')

*************
s = How do you do?
v =  5.00
t = (97.5, 82.9, 66.7)
l = [3.9, 5.7, 7.5, 9.3]
a = 
[3.9 5.7 7.5 9.3]
*************
*call "test"*
*************
s1 = I am doing fine 
v1 =  9.87
t1 = (1.1, 2.9)
l1 = [3.9, 5.7, 7.5, 'end']
a1 = 
[963.2   5.7   7.5   9.3]
*************
s = How do you do? 
v =  5.00
t = (97.5, 82.9, 66.7)
l = [3.9, 5.7, 7.5, 'end']
a = 
[963.2   5.7   7.5   9.3]
*************


We see that the values of the
string `s`, the numeric variable `v`, and the contents of `t` are
unchanged after the function call. 

The list `l` and the array `a`
are changed after the function call. 

-   Changes to string, variable, and tuple arguments of a function
    within the function do not affect their values in the calling
    program.
-   Changes to values of elements in list and array arguments of a
    function within the function are reflected in the values of the
    same list and array elements in the calling function.

Simple numerics, strings and tuples are immutable
while lists and arrays are mutable. 


# Funny things about list and numpy array

In [2]:
a=[1,2,3,4,5]
b=a
print(b)

[1, 2, 3, 4, 5]


In [3]:
del b[0]
print(b)

[2, 3, 4, 5]


In [4]:
print(a)

[2, 3, 4, 5]


In [5]:
import numpy as np
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
b=a
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
b[0]=10

In [9]:
b

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [10]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

* To make a copy of a list and a numpy array, we need to use the copy() function. Otherwise, 'b=a' only gives an other name for the same list/array. Each time you modify the elements of variable b or a will change the content of the variable.

In [11]:
a=[1,2,3,4,5]
b=a.copy()
del b[0]
print(a)
print(b)

[1, 2, 3, 4, 5]
[2, 3, 4, 5]


* This does not apply to tuple, since tuple is immutable.

In [12]:
a=(1,2,3,4,5,6)
a

(1, 2, 3, 4, 5, 6)

In [13]:
b=a
b[0]=10

TypeError: 'tuple' object does not support item assignment

## Anonymous functions (lambda)

A lambda expression is a kind of in-line function that can
be generated on the fly to accomplish some small task. 

You can assign
lambda functions a name, but you don't need to; hence, they are often
called *anonymous* functions. 

A lambda uses the keyword `lambda` and has
the general form:


```python
lambda arg1, arg2, ... : output
```

The arguments `arg1, arg2, ...` are inputs to a lambda, just as for a
functions, and the output is an expression using the arguments.

While lambda expressions need not be named, we illustrate their use by
comparing a conventional Python function definition to a lambda
expression to which we give a name. 

In [15]:
def f(a, b):  
    return 3*a + b**2

In [16]:
f(2,3)

15

Next, we define a lambda that does the same thing

In [ ]:
g = lambda a, b: 3 * a + b**2 

In [ ]:
g(2,3)

# [Exercise 09](./EX09-function.ipynb)

# [Exercise 10](./EX10-sorting-algorithm.ipynb)